sudo: false
language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - master

script:
  - hexo generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $travis_token
  keep-history: true
  on:
    all_branches: true
    branch: gh-pages
  local-dir: public
